# Generated by Django 6.0.1 on 2026-01-11 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('admin', models.BooleanField()),
                ('mobile', models.BigIntegerField()),
                ('email', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
